steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
  id: login
   
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMG_DEST}:latest'
    - '-f'
    - 'Dockerfile'
    - '.'
  id: build

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_IMG_DEST}:latest'
  id: push

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/bash
  args:
    - -c
    - |
        docker image inspect ${_IMG_DEST}:$SHORT_SHA --format '{{index .RepoDigests 0}}' > image-digest.txt &&
        cat image-digest.txt
  id: inspect

substitutions:
    _IMG_DEST: gregnrobinson/cloud-tools
    
availableSecrets:
  secretManager:
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_PASSWORD_SECRET}/versions/${_DOCKER_PASSWORD_SECRET_VERSION}
     env: 'PASSWORD'
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_ID_SECRET}/versions/${_DOCKER_ID_SECRET_VERSION}
     env: 'USERNAME'
