steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMG_DEST}:latest'
    - '-f'
    - 'Dockerfile'
    - '.'
  id: build

substitutions:
    _IMG_DEST: gregnrobinson/cloud-tools
     
timeout: 1200s