steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - '-c'
    - 'docker login'
    - '--username=$$DOCKER_USERNAME'
    - '--password=$$DOCKER_PASSWORD'
   secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
   id: login
   
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMG_DEST}:$SHORT_SHA'
    - '-f'
    - 'Dockerfile'
    - '.'
  id: build

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_IMG_DEST}:$SHORT_SHA'
  id: push

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - '${_IMG_DEST}:$SHORT_SHA'
    - '${_IMG_DEST}:latest'
  waitFor: ["build"]

images:
- '${_IMG_DEST}:latest'
- '${_IMG_DEST}:$SHORT_SHA'

substitutions:
    _IMG: cloud-tools
    _IMG_DEST: gregnrobinson/cloud-tools
    
availableSecrets:
  secretManager:
   - versionName: projects/PROJECT_ID/secrets/${_DOCKER_PASSWORD_SECRET}/versions/${_DOCKER_PASSWORD_SECRET_VERSION}
     env: 'DOCKER_PASSWORD'
   - versionName: projects/PROJECT_ID/secrets/${_DOCKER_ID_SECRET}/versions/${_DOCKER_ID_SECRET_VERSION}
     env: 'DOCKER_USERNAME'
