steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
  id: login

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'pull'
    - '${_IMG_DEST}:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - '${_IMG_DEST}:latest'
    - '${_IMG_DEST}:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - '${_IMG_DEST}:$SHORT_SHA'
    - '${_IMG_DEST}:latest'

substitutions:
    _IMG_DEST: gregnrobinson/cloud-tools
    
availableSecrets:
  secretManager:
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_PASSWORD_SECRET}/versions/${_DOCKER_PASSWORD_SECRET_VERSION}
     env: 'PASSWORD'
   - versionName: projects/${_PROJECT_ID}/secrets/${_DOCKER_ID_SECRET}/versions/${_DOCKER_ID_SECRET_VERSION}
     env: 'USERNAME'