steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMG_DEST}:$SHORT_SHA'
    - '-f'
    - './${_IMG}/Dockerfile'
    - './${_IMG}'
  id: build

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - '${_IMG_DEST}:$SHORT_SHA'
  id: push

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - '${_IMG_DEST}:$SHORT_SHA'
    - '${_IMG_DEST}:latest'
  waitFor: ["build"]

images:
- '${_IMG_DEST}:latest'
- '${_IMG_DEST}:$SHORT_SHA'
